// <auto-generated />
using System;
using LostFoundPetReporter.CoreDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostFoundPetReporter.CoreDb.Migrations
{
    [DbContext(typeof(PetReporterContext))]
    [Migration("20260825140607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundCoordinate", b =>
                {
                    b.Property<int>("FoundReportId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("FoundReportId");

                    b.ToTable("FoundCoordinate");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoundReports", (string)null);
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundReportExtFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("FoundReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId");

                    b.ToTable("FoundReportExtFiles", (string)null);
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostCoordinate", b =>
                {
                    b.Property<int>("LostReportId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("LostReportId");

                    b.ToTable("LostCoordinate");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostFoundMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoundReportId")
                        .HasColumnType("int");

                    b.Property<int>("LostReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId");

                    b.HasIndex("LostReportId", "FoundReportId")
                        .IsUnique();

                    b.ToTable("LostFoundMatches");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LostReports", (string)null);
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostReportExtFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("LostReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LostReportId");

                    b.ToTable("LostReportExtFiles", (string)null);
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundCoordinate", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.FoundReport", "FoundReportNavigation")
                        .WithOne("FoundCoordinateNavigation")
                        .HasForeignKey("LostFoundPetReporter.CoreDb.Models.FoundCoordinate", "FoundReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoundReportNavigation");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundReport", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.User", "UserNevigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LostFoundPetReporter.CoreDb.Models.AnimalDescription", "PetDescription", b1 =>
                        {
                            b1.Property<int>("FoundReportId")
                                .HasColumnType("int");

                            b1.Property<string>("Breed")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Colors")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FoundReportId");

                            b1.ToTable("FoundReports");

                            b1.WithOwner()
                                .HasForeignKey("FoundReportId");
                        });

                    b.Navigation("PetDescription")
                        .IsRequired();

                    b.Navigation("UserNevigation");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundReportExtFile", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.FoundReport", null)
                        .WithMany("FoundReportExtFilesNevigation")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostCoordinate", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.LostReport", "LostReportNavigation")
                        .WithOne("LostCoordinateNavigation")
                        .HasForeignKey("LostFoundPetReporter.CoreDb.Models.LostCoordinate", "LostReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LostReportNavigation");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostFoundMatch", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.FoundReport", "FoundReportNevigation")
                        .WithMany("LostFoundMatchNevigation")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LostFoundPetReporter.CoreDb.Models.LostReport", "LostReportNevigation")
                        .WithMany("LostFoundMatchNevigation")
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoundReportNevigation");

                    b.Navigation("LostReportNevigation");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostReport", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LostFoundPetReporter.CoreDb.Models.AnimalDescription", "PetDescription", b1 =>
                        {
                            b1.Property<int>("LostReportId")
                                .HasColumnType("int");

                            b1.Property<string>("Breed")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Colors")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LostReportId");

                            b1.ToTable("LostReports");

                            b1.WithOwner()
                                .HasForeignKey("LostReportId");
                        });

                    b.Navigation("PetDescription")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostReportExtFile", b =>
                {
                    b.HasOne("LostFoundPetReporter.CoreDb.Models.LostReport", null)
                        .WithMany("LostReportExtFilesNevigation")
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.FoundReport", b =>
                {
                    b.Navigation("FoundCoordinateNavigation");

                    b.Navigation("FoundReportExtFilesNevigation");

                    b.Navigation("LostFoundMatchNevigation");
                });

            modelBuilder.Entity("LostFoundPetReporter.CoreDb.Models.LostReport", b =>
                {
                    b.Navigation("LostCoordinateNavigation");

                    b.Navigation("LostFoundMatchNevigation");

                    b.Navigation("LostReportExtFilesNevigation");
                });
#pragma warning restore 612, 618
        }
    }
}
